#!/usr/bin/env python3
"""Write ultron/tv/BACKTEST_ALL.md from ultron/tv/backtest/results.json (made by backtest_all.py). No typed numbers."""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TV = os.path.join(os.path.dirname(HERE), "tv")
ORDER = ["5m", "15m", "30m", "1h", "2h", "4h", "1D", "1Dm"]
LABEL = {"1Dm": "1D markets", "1D": "1D crypto"}


def lab(tf):
    return LABEL.get(tf, tf + " crypto")


def acc(x):
    return f"{x[0]:.1f}% ({x[1]:,})" if x and x[0] is not None and x[1] else "–"


def mv(x):
    return f"{x:.2f}%" if x is not None else "–"


def main():
    with open(os.path.join(TV, "backtest", "results.json")) as fh:
        R = json.load(fh)
    tfs = [t for t in ORDER if t in R]
    L = []
    w = L.append
    w("# ULTRON indicators: full backtest on every timeframe")
    w("")
    w("Generated by `ultron/tools/report_all.py` from `ultron/tv/backtest/results.json`, which `ultron/tools/backtest_all.py`")
    w("produced from the same data and trained models the two indicators are built from. No number here was typed by hand.")
    w("Past results after costs, not a forecast, not financial advice.")
    w("")
    w("## How to read the numbers")
    w("")
    w("- **Periods.** *Fit* = data the models learned from (before 20 Mar 2025). *Validation* = 20 Mar – 22 Dec 2025, used only")
    w("  to accept or reject changes. *Test* = since 23 Dec 2025, never used to choose anything: the honest number.")
    w("- **Right X% (N calls).** Of the N bars where the Radar made that call, the share where it came true.")
    w("  LOUD comes true when the next 12 bars' high-to-low range lands in the top third of the last month's 12-bar")
    w("  ranges. QUIET comes true when it lands in the bottom third. **Chance** = how often that happens on any bar.")
    w("- **R.** One R = the amount you risk on a trade (entry to stop). +0.2R per trade = on average you made 20% of what")
    w("  you risked, after fees and slippage.")
    w("- **Win rate.** Share of trades that closed with a profit after fees. A high win rate alone means nothing: a")
    w("  strategy can win 90% of the time and still lose money if the losses are bigger than the wins. Read win rate")
    w("  together with avg R.")
    w("- **PF (profit factor).** Total won ÷ total lost. Above 1 = profitable.")
    w("- **Return / max DD.** On a $10,000 paper account with the Council's own position sizes. Max DD = worst drop from a")
    w("  high point.")
    w("")
    w("## 1. ULTRON Radar: is a big move coming?")
    w("")
    w("### Untouched test (since Dec 2025), all markets of each timeframe")
    w("")
    w("| Chart | LOUD right | VERY LOUD right | Chance of a big move | QUIET right | VERY QUIET right | Chance of a small move | AUC (big) |")
    w("|---|---|---|---|---|---|---|---|")
    for tf in tfs:
        r = R[tf]["radar"]["rows"].get("all|C")
        if not r:
            continue
        w(f"| {lab(tf)} | {acc(r['loud'])} | {acc(r['very_loud'])} | {r['base_loud']:.1f}% | {acc(r['quiet'])} | {acc(r['very_quiet'])} | "
          f"{r['base_quiet']:.1f}% | {r['auc_loud']:.3f} |")
    w("")
    w("### How big the next 12 bars moved after each call (median high-to-low range, test period)")
    w("")
    w("| Chart | Any bar | After QUIET | After LOUD | After VERY LOUD |")
    w("|---|---|---|---|---|")
    for tf in tfs:
        r = R[tf]["radar"]["rows"].get("all|C")
        if r:
            w(f"| {lab(tf)} | {mv(r['move_all'])} | {mv(r['move_quiet'])} | {mv(r['move_loud'])} | {mv(r['move_very_loud'])} |")
    w("")
    w("### Same calls in every period (does it hold up over time?)")
    w("")
    w("| Chart | LOUD right: fit / validation / test | VERY LOUD right: fit / validation / test | How often LOUD fires (test) |")
    w("|---|---|---|---|")
    for tf in tfs:
        rows = R[tf]["radar"]["rows"]
        f = lambda k, p: (lambda x: f"{x[0]:.0f}%" if x and x[0] is not None else "–")((rows.get(f"all|{p}") or {}).get(k))  # noqa: E731
        c = rows.get("all|C") or {}
        w(f"| {lab(tf)} | {f('loud', 'A')} / {f('loud', 'B')} / {f('loud', 'C')} | {f('very_loud', 'A')} / {f('very_loud', 'B')} / "
          f"{f('very_loud', 'C')} | {c.get('loud_share', 0):.1f}% of bars |")
    w("")
    w("### By market group (test period)")
    w("")
    w("| Chart | Group | LOUD right | VERY LOUD right | QUIET right | Chance (big) |")
    w("|---|---|---|---|---|---|")
    for tf in tfs:
        for key, r in sorted(R[tf]["radar"]["rows"].items()):
            grp, p_ = key.split("|")
            if p_ == "C" and grp != "all":
                w(f"| {lab(tf)} | {grp} | {acc(r['loud'])} | {acc(r['very_loud'])} | {acc(r['quiet'])} | {r['base_loud']:.1f}% |")
    w("")
    w("## 2. ULTRON Council: when to buy, and how each exit style did")
    w("")
    w("Every timeframe's walk-forward was re-run from the cached signals and reproduced the model file exactly. Then every")
    w("trade the Council took was replayed with each exit style: same buys, same sizes, different sells.")
    w("")
    for tf in tfs:
        cn = R[tf]["council"]
        w(f"### {lab(tf)}  ·  reproduces the model: {'yes' if cn['reproduces_model_file'] else 'NO'}  ·  replay check {cn['replay_matches_2R']}")
        w("")
        w("| Exit style | Trades | Win rate | Avg R | PF | Return | Max DD | Test: trades · win rate · avg R |")
        w("|---|---|---|---|---|---|---|---|")
        for name, m in cn["styles"].items():
            a, c = m["all"], m["C"]
            pf = f"{a['pf']:.2f}" if a.get("pf") else "–"
            tst = f"{c['n']} · {c['win']:.0f}% · {c['avg_r']:+.3f}R" if c["n"] else "–"
            w(f"| {name} | {a['n']} | {a['win']:.1f}% | {a['avg_r']:+.3f}R | {pf} | {a['ret']:+.1f}% | {a['mdd']:.1f}% | {tst} |")
        w("")
    with open(os.path.join(TV, "BACKTEST_ALL.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote BACKTEST_ALL.md")


if __name__ == "__main__":
    main()
