"""Write docs/CATALOG_BACKTEST_REPORT.md from a research ledger filled by scripts/catalog_batch.py.

Every number in the report is read from the ledger; nothing is typed in by hand.

    python scripts/catalog_report.py <home folder> [output.md]
"""

import json
import sqlite3
import sys
import time
from collections import Counter

ROOT = __file__.rsplit("/scripts/", 1)[0]
sys.path.insert(0, ROOT + "/backend")
sys.path.insert(0, ROOT + "/scripts")

from catalog_batch import PLAN, template                       # noqa: E402
from tradingai.research.portfolio import PORTFOLIOS            # noqa: E402
from tradingai.strategies import catalog                        # noqa: E402


def pct(v, dp=1):
    return "—" if v is None else f"{v * 100:.{dp}f}%"


def num(v, dp=2):
    return "—" if v is None else f"{v:.{dp}f}"


def day(ms):
    return time.strftime("%Y-%m-%d", time.gmtime(ms / 1000)) if ms else "—"


def load(home):
    db = sqlite3.connect(f"{home}/data/app.sqlite3")
    db.row_factory = sqlite3.Row
    rows = []
    for r in db.execute("SELECT * FROM experiments ORDER BY created"):
        d = dict(r)
        d["results"] = json.loads(d["results"]) if d["results"] else None
        d["dataset"] = json.loads(d["dataset"])
        rows.append(d)
    return rows


def main(home, out):
    rows = load(home)
    cards = {c["id"]: c for c in catalog.load()["cards"]}
    lines = []
    w = lines.append

    port = [r for r in rows if r["dataset"].get("instrument", "").startswith("PORTFOLIO:")]
    single = [r for r in rows if not r["dataset"].get("instrument", "").startswith("PORTFOLIO:")]
    first, last = min(r["created"] for r in rows), max(r["created"] for r in rows)
    w("# Catalog backtest report")
    w("")
    w(f"Generated by `scripts/catalog_report.py` from the research ledger of one batch run "
      f"(`scripts/catalog_batch.py`, {day(first)}, code version {rows[0]['code_version']}). "
      f"{len(port)} portfolio runs and {len(single)} single-market runs, all on real historical data "
      f"downloaded by the app (Yahoo Finance and Coinbase public endpoints). Every number below is read from that "
      f"ledger.")
    w("")
    w("**How to read this.** \"Published evidence\" is the label your specification gives each template "
      "(R research-supported, C documented construction, H hypothesis). \"Here\" is what this software measured on "
      "its own data, net of modelled costs, on a held-out period it never tuned on. The two are different things: "
      "a study can be right about its own sample and a template can still fail on a short, recent, small universe. "
      "Results describe past data under the stated assumptions. They are not a promise of future returns.")
    w("")
    verdicts = Counter((r["results"] or {}).get("verdict") or r["status"] for r in rows)
    ok = [r for r in rows if (r["results"] or {}).get("status") == "ok"]
    dsr_fail = sum(1 for r in ok if any(not c["passed"] and c["name"].startswith("deflated Sharpe")
                                        for c in r["results"]["checks"]))
    best = max(ok, key=lambda r: r["results"]["statistics"].get("dsr") or 0, default=None)
    head = ", ".join(f"{v} {k}" for k, v in verdicts.most_common()) + ". "
    head += ("No template reached PAPER TEST. " if not verdicts.get("PAPER TEST") else "")
    head += (f"{dsr_fail} of {len(ok)} completed runs failed the Deflated Sharpe gate (≥ 0.95), which charges every "
             f"parameter set ever tried in the same family. ")
    if best:
        head += (f"The highest Deflated Sharpe was {best['results']['statistics']['dsr']:.3f}: "
                 f"{best['strategy_id']} on {best['dataset'].get('instrument')}.")
    w("**Headline.** " + head)
    w("")

    # ------------------------------------------------------------------ portfolio templates
    w("## Portfolio templates (multi-asset, rebalanced)")
    w("")
    w("Weights are decided at a rebalance close using only data up to that close and filled at the next day's "
      "close. The first 70% of the shared history tunes the parameters; the last 30% is held out. The benchmark "
      "is an equal-weight holding of the same universe over the same held-out days.")
    w("")
    w("| ID | Template | Published | Held out | Return | Sharpe | Equal-wt Sharpe | Max DD | Equal-wt DD "
      "| Sharpe 2× costs | DSR | Beats EW | Verdict |")
    w("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in port:
        res = r["results"] or {}
        sid = r["strategy_id"]
        card = cards.get(sid.split("-")[0], {})
        if res.get("status") != "ok":
            w(f"| {sid} | {PORTFOLIOS[sid].name} | {card.get('evidence', '—')} | — | — | — | — | — | — | — | — | — "
              f"| {res.get('status') or r['status']} |")
            continue
        t, b, c2, st = res["test"], res["benchmark_test"], res["cost_2x_test"], res["statistics"]
        beats = next((c["passed"] for c in res["checks"] if c["name"].startswith("beats")), None)
        w(f"| {sid} | {res['name']} | {card.get('evidence', '—')} | {day(res['split_day'])} → "
          f"{day(r['dataset']['end'])} ({num(t['years'], 1)} y) | {pct(t['total_return'])} | {num(t['sharpe'])} "
          f"| {num(b['sharpe'])} | {pct(t['max_drawdown'])} | {pct(b['max_drawdown'])} | {num(c2['sharpe'])} "
          f"| {num(st['dsr'], 3)} | {'yes' if beats else 'no'} | {res['verdict']} |")
    w("")
    w("Limitations recorded with each run:")
    w("")
    for r in port:
        res = r["results"] or {}
        lim = res.get("limitations") or PORTFOLIOS[r["strategy_id"]].limitations
        cap = PORTFOLIOS[r["strategy_id"]].max_verdict
        parts = (["; ".join(lim) + "."] if lim else []) + ([f"Verdict capped at {cap}."] if cap != "PAPER TEST" else [])
        if parts:
            w(f"- **{r['strategy_id']}**: {' '.join(parts)}")
    w("")

    # ------------------------------------------------------------------ single-market templates
    w("## Single-market templates")
    w("")
    w("Chronological train / validation / test split; parameters chosen on train only; walk-forward folds; "
      "Deflated Sharpe charged with every trial in the family; PBO across the parameter grid; a random-entry "
      "placebo. Fewer than 30 test trades cannot pass.")
    w("")
    queue: dict[tuple, list[dict]] = {}
    for r in single:
        queue.setdefault((r["strategy_id"], r["dataset"].get("instrument"), r["dataset"].get("tf")), []).append(r)
    w("| Card | Published | Template | Market | TF | Data | Test trades | Test return | Test Sharpe "
      "| WF OOS Sharpe | DSR | PBO | Verdict | Failed gates |")
    w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    per_card: dict[str, Counter] = {}
    for card_id, gens in PLAN.items():
        for gen, targets in gens.items():
            sid = template(gen)
            for iid, tf in targets:
                runs = queue.get((sid, iid, tf), [])
                r = runs.pop(0) if runs else None
                ev = cards[card_id]["evidence"]
                if r is None:
                    w(f"| {card_id} | {ev} | `{sid}` | {iid} | {tf} | — | — | — | — | — | — | — | not run "
                      f"| refused before it ran (no ledger entry; the batch log gives the reason) |")
                    per_card.setdefault(card_id, Counter())["not run"] += 1
                    continue
                res = r["results"] or {}
                if res.get("status") != "ok":
                    why = (r["reason"] or res.get("status") or r["status"])[:90]
                    w(f"| {card_id} | {ev} | `{sid}` | {iid} | {tf} | — | — | — | — | — | — | — | "
                      f"{r['status']} | {why} |")
                    per_card.setdefault(card_id, Counter())[r["status"]] += 1
                    continue
                t, st, ds = res["test"], res["statistics"], r["dataset"]
                failed = [c["name"] for c in res["checks"] if not c["passed"]]
                big = " (CONTRACT_TOO_LARGE)" if "CONTRACT_TOO_LARGE" in res.get("reason_codes", []) else ""
                w(f"| {card_id} | {ev} | `{sid}` | {iid} | {tf} | {day(ds['start'])} → {day(ds['end'])} "
                  f"| {t['trades']} | {pct(t['total_return'])} | {num(t['sharpe'])} "
                  f"| {num(res['walk_forward'].get('oos_sharpe'))} | {num(st['dsr'], 3)} | {num(st.get('pbo'))} "
                  f"| {res['verdict']}{big} | {', '.join(failed) or 'none'} |")
                per_card.setdefault(card_id, Counter())[res["verdict"]] += 1
    w("")
    w("Per card:")
    w("")
    for card_id, cnt in per_card.items():
        w(f"- **{card_id} {cards[card_id]['name']}** (published {cards[card_id]['evidence']}): "
          + ", ".join(f"{v} {k}" for k, v in cnt.most_common()))
    w("")

    # ------------------------------------------------------------------ catalog coverage
    view = catalog.view([], set(), set())
    w("## All 80 templates: what this software can and cannot test")
    w("")
    states = Counter(c["state"] for c in view)
    w("States before any backtest: " + ", ".join(f"{v} {k}" for k, v in states.most_common()) + ". "
      "\"documented\" and \"specified\" templates need data or products this installation does not have; the "
      "reason code says which.")
    w("")
    w("| ID | Template | Published | Implemented by | Blocked by |")
    w("|---|---|---|---|---|")
    for c in view:
        w(f"| {c['id']} | {c['name']} | {c['evidence']} | {', '.join(c['implementations']) or '—'} "
          f"| {c['blocked'] or ''} |")
    w("")

    w("## Caveats that apply to every number above")
    w("")
    w("- **Survivorship bias.** Stock universes are today's large companies; there is no point-in-time "
      "membership or delisting data. Those templates are capped at RESEARCH FURTHER.")
    w("- **Continuous futures.** Futures use the provider's continuous series, not real contract rolls; roll "
      "costs and roll timing are approximations. Futures portfolios are research-only (not deployable here).")
    w("- **Contract size.** Single-market tests start with 100,000 USD and size trend trades to a 15% volatility "
      "target. One ES or gold contract is worth several times that, so those signals cannot be traded at all; "
      "such runs carry CONTRACT_TOO_LARGE and say nothing about the signal. The micro E-mini (MES, one tenth of "
      "ES) is tested alongside for that reason.")
    w("- **Long-only adaptations.** Spot crypto and stock templates that are long/short in the literature are "
      "run long/flat here; that is a different strategy from the published one.")
    w("- **Short, recent histories.** Crypto has at most about eleven years of daily data (SOL far less), and "
      "intraday data from free providers covers weeks to months, so intraday tests have few trades.")
    w("- **Modelled costs.** Fees, spread and slippage are assumptions (edit them to match your broker); every "
      "template is also shown at 2× costs.")
    w("- **Multiple testing.** Every run is a trial; the Deflated Sharpe bar rises with every run in a family, "
      "including the runs in this batch.")
    w("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(port)} portfolio + {len(single)} single-market runs")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else ROOT + "/docs/CATALOG_BACKTEST_REPORT.md")
