#!/usr/bin/env python3
"""Write ULTRON_Radar.pine: the trained volatility forecast (LOUD / NORMAL / QUIET for the next 12 bars) for every
timeframe, plus trend, an ATR stop, fee cost in R and position size. Works on any chart; the table says whether the
forecast was trained on this timeframe and market or is the nearest model.

  python3 ultron/tv/build_radar.py      (uses ultron/tv/models/*.json, same as build_pine.py)
"""

from __future__ import annotations

import math
import os

from build_pine import HERE, HTF, HTF_SEC, SEC, load_models, num


def build(models):
    cm = [m for m in models if not m.get("market")]
    nmc = len(cm)
    mkt = models[nmc] if len(models) > nmc else None
    tag = lambda m: m["tf"] + (" markets" if m.get("market") else " crypto")   # noqa: E731
    L = []
    w = L.append
    w("// ULTRON Radar · generated by ultron/tv/build_radar.py from the trained models. Educational, not advice.")
    w("//@version=5")
    w('indicator("ULTRON Radar · volatility forecast, trend, stop and size", shorttitle="ULTRON Radar", overlay=true, max_bars_back=5000)')
    w("")
    w('gA = "Your account"')
    w('iAccount = input.float(1000, "Account size ($)", minval=10, group=gA)')
    w('iRisk = input.float(0.5, "Risk per trade (%)", minval=0.05, maxval=5, step=0.05, group=gA)')
    w('iFeeC = input.float(0.20, "Crypto: fee per side (%)", minval=0, step=0.01, group=gA, tooltip="NDAX 0.20 · Kraken Pro 0.25-0.40 · Coinbase 0.40-0.60")')
    w('iFeeM = input.float(0.05, "Stocks, ETFs, forex: cost per side (%)", minval=0, step=0.01, group=gA)')
    w('gS = "Stop and target"')
    w('iStopX = input.float(1.0, "Stop distance (x the trained stop)", minval=0.25, step=0.05, group=gS, tooltip="Trained stop: 4x ATR on 1h and slower, wider on 5m-30m.")')
    w('iTargetR = input.float(2.0, "Target (R)", minval=0.5, step=0.25, group=gS)')
    w('iLines = input.bool(true, "Draw the stop and target for a long entered now", group=gS)')
    w('gD = "Display"')
    w('iTable = input.bool(true, "Show the table", group=gD)')
    w('iPos = input.string("Top right", "Table position", options=["Top right", "Top left", "Bottom right", "Bottom left"], group=gD)')
    w('iText = input.string("Small", "Table text", options=["Tiny", "Small", "Normal"], group=gD)')
    w('iTintL = input.bool(true, "Tint LOUD periods", group=gD)')
    w('iTintQ = input.bool(true, "Tint QUIET periods", group=gD)')
    w('cLoud = input.color(color.new(#1F5BFF, 90), "LOUD", group=gD, inline="c")')
    w('cQuiet = input.color(color.new(#8A94A6, 92), "QUIET", group=gD, inline="c")')
    w('cStop = input.color(color.new(#E2474D, 0), "Stop", group=gD, inline="c")')
    w('cTarget = input.color(color.new(#0E9F63, 0), "Target", group=gD, inline="c")')
    w("")
    w("// ═════════ which model: this chart's timeframe, or the nearest trained one")
    w('isMarket = syminfo.type != "crypto"')
    w("tfSec = timeframe.in_seconds()")
    secs = [SEC[m["tf"]] for m in cm]
    w("exactC = " + " or ".join(f"tfSec == {s}" for s in secs))
    w("miC = " + "".join(f"tfSec < {int(math.sqrt(secs[k] * secs[k + 1]))} ? {k} : " for k in range(nmc - 1)) + str(nmc - 1))
    if mkt:
        w(f"useMkt = isMarket and tfSec == 86400")
        w(f"mi = useMkt ? {nmc} : miC")
        w("exact = useMkt or (not isMarket and exactC)")
    else:
        w("mi = miC")
        w("exact = not isMarket and exactC")
    w('mName = ' + "".join(f'mi == {k} ? "{tag(m)}" : ' for k, m in enumerate(models[:-1])) + f'"{tag(models[-1])}"')
    w('htfStr = ' + "".join(f'mi == {k} ? "{HTF[m["tf"]]}" : ' for k, m in enumerate(models[:-1])) + f'"{HTF[models[-1]["tf"]]}"')
    G = [m["gate"] for m in models]
    arr = lambda xs, d: "array.from(" + ", ".join(num(x, d) for x in xs) + ")"      # noqa: E731
    w(f"var float[] G_MU = {arr([x for g in G for x in g['mean']], 8)}")
    w(f"var float[] G_SD = {arr([x for g in G for x in g['std']], 8)}")
    w(f"var float[] G_WL = {arr([x for g in G for x in g['w_loud']], 8)}")
    w(f"var float[] G_WQ = {arr([x for g in G for x in g['w_quiet']], 8)}")
    w(f"var float[] G_TL = {arr([g['t_loud'] for g in G], 6)}")
    w(f"var float[] G_TQ = {arr([g['t_quiet'] for g in G], 6)}")
    sc = [g["scores"]["C"] for g in G]
    pr = lambda x: f"{x:.0f}%" if x is not None else "n/a"                          # noqa: E731
    w("var string[] G_PL = array.from(" + ", ".join(f'"{pr(s["loud_precision"])}"' for s in sc) + ")")
    w("var string[] G_PQ = array.from(" + ", ".join(f'"{pr(s["quiet_precision"])}"' for s in sc) + ")")
    w("var string[] G_BASE = array.from(" + ", ".join(f'"{pr(s["base_rate"])}"' for s in sc) + ")")
    X = [m.get("exit", {"stop_chart": 4.0}) for m in models]
    w(f"var float[] P_SC = {arr([x['stop_chart'] for x in X], 3)}")
    win = [min(720, max(120, 30 * max(1, round(86400 / SEC[m['tf']])))) for m in models]
    w(f"var int[] G_WIN = array.from({', '.join(map(str, win))})")
    w("")
    w("// ═════════ the volatility forecast (14 features, logistic model trained on this timeframe)")
    w("atrC = ta.atr(14)")
    w("lg(x) => math.log(math.max(1e-6, x))")
    w("lr = nz(math.log(close / close[1]))")
    w("rms(k) => math.sqrt(math.sum(lr * lr, k) / k)")
    w("bbw = 4 * ta.stdev(close, 20) / ta.sma(close, 20)")
    w("r12 = (ta.highest(high, 12) - ta.lowest(low, 12)) / close")
    w("r72 = (ta.highest(high, 72) - ta.lowest(low, 72)) / close")
    w('hr = hour(time, "UTC")')
    w('dw = dayofweek(time, "UTC")')
    w("vsd = ta.stdev(volume, 168)")
    w("feat = array.from(1.0, lg(atrC / ta.sma(atrC, 168)), lg(bbw / ta.sma(bbw, 168)), "
      "lg((math.sum(volume, 6) / 6 + 1e-12) / (ta.sma(volume, 168) + 1e-12)), lg(rms(24) / rms(168)), lg(r12 / ta.sma(r12, 168)), "
      "math.min(6.0, math.abs(close - close[12]) / atrC), math.min(6.0, (high - low) / atrC), "
      "math.sin(2 * math.pi * hr / 24), math.cos(2 * math.pi * hr / 24), dw == dayofweek.saturday or dw == dayofweek.sunday ? 1.0 : 0.0, "
      "lg(rms(6) / rms(168)), lg(r72 / ta.sma(r72, 168)), "
      "math.max(-4.0, math.min(4.0, (ta.sma(volume, 24) - ta.sma(volume, 168)) / (vsd > 0 ? vsd : 1e-12))))")
    w("zl = 0.0")
    w("zq = 0.0")
    w("bad = bar_index < 248")
    w("gOff = mi * 14")
    w("for k = 0 to 13")
    w("    x = array.get(feat, k)")
    w("    if na(x)")
    w("        bad := true")
    w("    else")
    w("        zz = (x - array.get(G_MU, gOff + k)) / array.get(G_SD, gOff + k)")
    w("        zl += zz * array.get(G_WL, gOff + k)")
    w("        zq += zz * array.get(G_WQ, gOff + k)")
    w('gate = bad ? "U" : 1 / (1 + math.exp(-zl)) >= array.get(G_TL, mi) ? "L" : 1 / (1 + math.exp(-zq)) >= array.get(G_TQ, mi) ? "Q" : "N"')
    w("// what LOUD and QUIET mean here: the next 12 bars' high-low range vs the last month of finished 12-bar ranges")
    w("rngDone = (ta.highest(high, 12) - ta.lowest(low, 12)) / close[12]")
    w("winN = array.get(G_WIN, mi)")
    for n_ in (720, 360, 180, 120):
        w(f"big{n_} = ta.percentile_nearest_rank(rngDone, {n_}, 66.67)")
        w(f"small{n_} = ta.percentile_nearest_rank(rngDone, {n_}, 33.33)")
    w("bigCutW = winN >= 720 ? big720 : winN >= 360 ? big360 : winN >= 180 ? big180 : big120")
    w("smallCutW = winN >= 720 ? small720 : winN >= 360 ? small360 : winN >= 180 ? small180 : small120")
    w("")
    w("// ═════════ trend, stop, fee cost, size")
    w("up1 = ta.ema(close, 21) > ta.ema(close, 50) and close > ta.ema(close, 200)")
    w("dn1 = ta.ema(close, 21) < ta.ema(close, 50) and close < ta.ema(close, 200)")
    w("f_uph() => close > ta.ema(close, 50) and ta.ema(close, 21) > ta.ema(close, 50)")
    w("upH = request.security(syminfo.tickerid, htfStr, f_uph()[1], lookahead=barmerge.lookahead_on)")
    w("stopD = iStopX * array.get(P_SC, mi) * atrC")
    w("stopPct = stopD / close * 100")
    w("fee = isMarket ? iFeeM : iFeeC")
    w("slip = isMarket ? 0.02 : (syminfo.basecurrency == \"BTC\" or syminfo.basecurrency == \"ETH\" or syminfo.basecurrency == \"SOL\" ? 0.02 : 0.10)")
    w("costR = (2 * fee + 2 * slip) / stopPct")
    w("qty = math.min(iAccount * iRisk / 100 / stopD, iAccount / close)")
    w("")
    w("// ═════════ chart")
    w('bgcolor(iTintL and gate == "L" ? cLoud : iTintQ and gate == "Q" ? cQuiet : na, title="Volatility forecast")')
    w("var line lS = na")
    w("var line lT = na")
    w("if barstate.islast and iLines and not na(stopD)")
    w("    line.delete(lS)")
    w("    line.delete(lT)")
    w("    lS := line.new(bar_index - 5, close - stopD, bar_index + 15, close - stopD, color=cStop, style=line.style_dashed)")
    w("    lT := line.new(bar_index - 5, close + iTargetR * stopD, bar_index + 15, close + iTargetR * stopD, color=cTarget, style=line.style_dashed)")
    w('loudStart = gate == "L" and gate[1] != "L"')
    w('quietStart = gate == "Q" and gate[1] != "Q"')
    w('plotshape(loudStart, "LOUD starts", shape.diamond, location.top, color.new(#1F5BFF, 0), size=size.tiny)')
    w('alertcondition(loudStart, "ULTRON Radar: LOUD", "ULTRON Radar: {{ticker}} LOUD, a big move is likely in the next 12 bars (direction unknown)")')
    w('alertcondition(quietStart, "ULTRON Radar: QUIET", "ULTRON Radar: {{ticker}} QUIET, a small move is likely: fees eat small moves")')
    w("if barstate.isconfirmed and loudStart")
    w('    alert("ULTRON Radar: " + syminfo.ticker + " LOUD · a big move is likely in the next 12 bars (direction unknown) · range > " + '
      'str.tostring(bigCutW * 100, "#.##") + "%", alert.freq_once_per_bar_close)')
    w("")
    w("// ═════════ table")
    w('posT = iPos == "Top right" ? position.top_right : iPos == "Top left" ? position.top_left : iPos == "Bottom right" ? position.bottom_right : position.bottom_left')
    w('tsz = iText == "Tiny" ? size.tiny : iText == "Normal" ? size.normal : size.small')
    w("var table T = table.new(posT, 2, 10, bgcolor=color.white, frame_color=#D9E0EB, frame_width=1, border_color=#E9EEF5, border_width=1)")
    w("ink = #0A1426")
    w("dim = #56657C")
    w("cell(r, a, b, col) =>")
    w("    table.cell(T, 0, r, a, text_color=dim, text_size=tsz, text_halign=text.align_left)")
    w("    table.cell(T, 1, r, b, text_color=col, text_size=tsz, text_halign=text.align_left)")
    w("px(x) => str.tostring(x, format.mintick)")
    w("if barstate.islast and iTable")
    w('    table.cell(T, 0, 0, "ULTRON RADAR", text_color=color.white, bgcolor=#1F5BFF, text_size=tsz)')
    w('    table.cell(T, 1, 0, mName + (exact ? " model" : " model (nearest, untested here)"), text_color=color.white, bgcolor=#1F5BFF, text_size=tsz)')
    w('    gTxt = gate == "L" ? "LOUD · big move likely" : gate == "Q" ? "QUIET · small move likely" : gate == "N" ? "NORMAL" : "warming up"')
    w('    cell(1, "Next 12 bars", gTxt, gate == "L" ? #1F5BFF : ink)')
    w('    cell(2, "Big / small move", "range > " + str.tostring(bigCutW * 100, "#.##") + "% / < " + str.tostring(smallCutW * 100, "#.##") + "%", ink)')
    w('    cell(3, "Right in testing", "LOUD " + array.get(G_PL, mi) + " · QUIET " + array.get(G_PQ, mi) + " (chance alone " + array.get(G_BASE, mi) + ")", ink)')
    w('    cell(4, "Direction", "not forecast: nobody can, reliably", dim)')
    w('    cell(5, "Trend chart / higher", (up1 ? "up" : dn1 ? "down" : "mixed") + " / " + (upH ? "up" : "not up"), up1 and upH ? cTarget : dn1 ? cStop : ink)')
    w('    cell(6, "Long stop / target", px(close - stopD) + " (-" + str.tostring(stopPct, "#.##") + "%) / " + px(close + iTargetR * stopD), ink)')
    w('    cell(7, "Fee cost", str.tostring(costR, "#.##") + "R · " + (costR <= 0.20 ? "OK" : costR <= 0.33 ? "costly: half size" : "too expensive: skip"), costR <= 0.20 ? cTarget : costR <= 0.33 ? ink : cStop)')
    w('    cell(8, "Size for " + str.tostring(iRisk) + "% risk", str.tostring(qty, "#.####") + " units ($" + str.tostring(qty * close, "#,###") + ")", ink)')
    w('    cell(9, "Not advice", "volatility, not direction", #97A3B6)')
    return "\n".join(L) + "\n"


def main():
    models = load_models()
    src = build(models)
    with open(os.path.join(HERE, "ULTRON_Radar.pine"), "w") as fh:
        fh.write(src)
    print(f"wrote ULTRON_Radar.pine: {len(src.splitlines())} lines; models {[m['tf'] + ('m' if m.get('market') else '') for m in models]}")


if __name__ == "__main__":
    main()
