#!/usr/bin/env python3
"""Write ULTRON 25 for TradingView (Pine Script v5) from the trained model: an indicator and a strategy.

  python3 ultron/tv/build_pine.py          # reads ultron/tv/tv_model.json, writes ULTRON_25_indicator.pine + _strategy.pine

Everything trained is inserted as constants: the 25 agents (signal, timeframe, condition, market group), the
brain's learned edge for each agent in each Bitcoin regime, the brain's settings, and the volatility gate's
weights. Every number in the chart's council comes from the same formulas the Python backtest used.
Re-run train.py --tv and this script to retrain.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "core"))
from brain import Brain  # noqa: E402

# Pine translations of signals.py, evaluated inside f_all() (works on the chart's 1h bars and inside the 4h request).
SNIP = {
    "hammer": "f_dn(0) and ham",
    "hanging_man": "f_up(0) and ham",
    "shooting_star": "f_up(0) and inv",
    "inverted_hammer": "f_dn(0) and inv",
    "doji_after_drop": "f_dn(0) and doji",
    "doji_after_rise": "f_up(0) and doji",
    "spinning_top": "body <= 0.3 * rng and body >= 0.1 * rng and upw >= body and loww >= body",
    "bear_engulfing": "f_up(1) and isBull[1] and isBear and close <= open[1] and open >= close[1] and body > body[1]",
    "bull_engulfing": "f_dn(1) and isBear[1] and isBull and close >= open[1] and open <= close[1] and body > body[1]",
    "outside_bar_up": "high > high[1] and low < low[1] and close > high[1]",
    "outside_bar_down": "high > high[1] and low < low[1] and close < low[1]",
    "inside_bar": "ins",
    "inside_bar_break_down": "ins[1] and close < low[2]",
    "inside_bar_break_up": "ins[1] and close > high[2]",
    "big_bull_bar": "isBull and rng >= 2 * A[1] and body >= 0.6 * rng",
    "big_bear_bar": "isBear and rng >= 2 * A[1] and body >= 0.6 * rng",
    "bull_marubozu": "isBull and body >= 0.9 * rng and rng >= A",
    "five_green": "g5 and not g5[1]",
    "five_red": "r5 and not r5[1]",
    "vol_spike_bull": "rvol >= 3 and isBull and body >= 0.5 * rng",
    "vol_spike_bear": "rvol >= 3 and isBear and body >= 0.5 * rng",
    "mfi_ob": "mf > 80 and mf[1] <= 80",
    "mfi_os": "mf < 20 and mf[1] >= 20",
    "bb_above": "close > bbU and close[1] <= bbU[1]",
    "bb_below": "close < bbL and close[1] >= bbL[1]",
    "obv_lead": "obvLead and not obvLead[1]",
    "obv_confirm": "obvConf and not obvConf[1]",
    "donchian20": "don20 and not don20[1]",
    "rsi_ob_70": "rsi14 > 70 and rsi14[1] <= 70",
    "rsi_os_30": "rsi14 < 30 and rsi14[1] >= 30",
    "keltner_up": "close > kcU and close[1] <= kcU[1]",
}
WHEN = {"any": "any time", "loud": "big moves", "trend": "uptrends", "loudtrend": "big moves + uptrend"}
VAR = {"any": 0, "loud": 1, "trend": 2, "loudtrend": 3}


def parse_key(s):
    p = s.split("|")
    if p[0] == "fleet":
        return ("fleet",)
    if p[0] == "fam":
        return ("fam", p[1], p[2])
    cid = "|".join(p[1:5])
    if p[0] == "a":
        return ("a", cid)
    if p[0] == "ag":
        return ("ag", cid, p[5])
    return ("agr", cid, p[5], {"True": True, "False": False}.get(p[6]))


def num(x, d=6):
    return f"{x:.{d}f}".rstrip("0").rstrip(".") if x == x else "na"


def build(model, strategy):
    P = model["params"]
    g = model["gate"]
    brain = Brain(P, {parse_key(k): v for k, v in model["stats"].items()})
    agents = model["agents"]
    sigs = sorted({a["signal"] for a in agents})
    missing = [s for s in sigs if s not in SNIP]
    if missing:
        raise SystemExit(f"no Pine translation for: {missing}")
    sidx = {s: k for k, s in enumerate(sigs)}
    m_t, s_t, m_f, s_f, m_n, s_n = [], [], [], [], [], []
    for a in agents:
        ev = {"agent": a["id"], "fam": a["family"], "group": a["group"], "gate": "L"}
        for b, M, S in ((True, m_t, s_t), (False, m_f, s_f), (None, m_n, s_n)):
            m, se, _ = brain.estimate(dict(ev, bull=b))
            M.append(m)
            S.append(se)
    arr = lambda xs, d=5: "array.from(" + ", ".join(num(x, d) for x in xs) + ")"            # noqa: E731
    L = []
    w = L.append
    title = "ULTRON 25 · AI trade council" + (" (strategy)" if strategy else "")
    w("// This source code is generated by ultron/tv/build_pine.py from the trained model. Educational, not advice.")
    w(f"// Trained {model['trained']} on Coinbase hourly data to {model['data_end']}. 25 agents, one learned brain.")
    w("//@version=5")
    if strategy:
        w(f'strategy("{title}", shorttitle="ULTRON 25", overlay=true, pyramiding=0, initial_capital=1000, '
          'default_qty_type=strategy.fixed, commission_type=strategy.commission.percent, commission_value=0.2, '
          'slippage=2, process_orders_on_close=false, calc_on_every_tick=false, max_labels_count=500, max_lines_count=500)')
    else:
        w(f'indicator("{title}", shorttitle="ULTRON 25", overlay=true, max_labels_count=500, max_lines_count=500)')
    w("")
    w("// ───────────────────────── inputs (change anything; the trained values are the defaults)")
    w('gA = "Account & risk"')
    w('iAccount = input.float(1000, "Account size ($)", minval=10, group=gA)' if not strategy else
      'iAccount = strategy.equity')
    w(f'iRiskMaj = input.float({P["risk_major"] * 100:.2f}, "Risk per trade: BTC, ETH, SOL (%)", minval=0.05, maxval=5, step=0.05, group=gA)')
    w(f'iRiskMem = input.float({P["risk_meme"] * 100:.2f}, "Risk per trade: meme coins (%)", minval=0.05, maxval=5, step=0.05, group=gA)')
    w('gF = "Your exchange fees"')
    w('iMaker = input.float(0.20, "Maker fee per side (%)", minval=0, step=0.01, group=gF, tooltip="NDAX 0.20 · Kraken Pro entry tier 0.40 · Coinbase Advanced 0.60")')
    w('iTaker = input.float(0.20, "Taker fee per side (%)", minval=0, step=0.01, group=gF, tooltip="NDAX 0.20 · Kraken Pro entry tier 0.80 · Coinbase Advanced 1.20")')
    w('gB = "Brain (trained defaults)"')
    w(f'iTheta = input.float({P["theta"]:.2f}, "Minimum learned edge (R)", step=0.01, group=gB, tooltip="The council approves a signal only if its learned edge minus caution x uncertainty is at least this.")')
    w(f'iZ = input.float({P["z"]:.2f}, "Caution (x uncertainty)", minval=0, step=0.25, group=gB)')
    w('iGate = input.string("LOUD only (trained)", "Volatility filter", options=["LOUD only (trained)", "LOUD or NORMAL", "Off"], group=gB)')
    w('iCostMax = input.float(0.33, "Max fee cost (R)", minval=0.05, step=0.01, group=gB)')
    w('iStopMult = input.float(4.0, "Stop distance (x ATR of the agent\'s timeframe)", minval=0.5, step=0.25, group=gB)')
    w('iTargetR = input.float(2.0, "Target (R)", minval=0.5, step=0.25, group=gB)')
    w('iOrderBars = input.int(3, "Limit order valid (bars)", minval=1, group=gB)')
    w('iHold = input.int(96, "Max hold (hours)", minval=4, group=gB)')
    w('iOther = input.bool(false, "Also run on markets it was not trained on", group=gB)')
    w('gG = "The 25 agents (switch any off)"')
    for k, a in enumerate(agents):
        lab = f'{a["name"]} · {a["label"]} · {a["tf"]} · {WHEN[a["variant"]]} · {a["group"]}'.replace('"', "'")
        w(f'a{k:02d} = input.bool(true, "{lab}", group=gG)')
    w('gD = "Display"')
    w('iTable = input.bool(true, "Show the council table", group=gD)')
    w('iTablePos = input.string("Top right", "Table position", options=["Top right", "Top left", "Bottom right", "Bottom left"], group=gD)')
    w('iTableSize = input.string("Small", "Table text", options=["Tiny", "Small", "Normal"], group=gD)')
    w('iPast = input.bool(true, "Mark past council buys", group=gD)')
    w('iLines = input.bool(true, "Draw entry, stop and target", group=gD)')
    w('iGateBg = input.bool(true, "Tint the background in LOUD periods", group=gD)')
    w('iMsg = input.string("Readable", "Alert message", options=["Readable", "JSON (for bots and webhooks)"], group=gD)')
    w('cBuy = input.color(color.new(#1F5BFF, 0), "Buy", group=gD, inline="c")')
    w('cStop = input.color(color.new(#E2474D, 0), "Stop", group=gD, inline="c")')
    w('cTarget = input.color(color.new(#0E9F63, 0), "Target", group=gD, inline="c")')
    w('cLoud = input.color(color.new(#1F5BFF, 93), "LOUD tint", group=gD, inline="c")')
    w("")
    w("// ───────────────────────── trained constants")
    w(f"var string[] NAMES = array.from({', '.join(chr(34) + a['name'] + chr(34) for a in agents)})")
    w(f"var string[] LABELS = array.from({', '.join(chr(34) + a['label'].replace(chr(34), '') + chr(34) for a in agents)})")
    w(f"var int[] SIG = array.from({', '.join(str(sidx[a['signal']]) for a in agents)})")
    w(f"var bool[] IS4H = array.from({', '.join('true' if a['tf'] == '4h' else 'false' for a in agents)})")
    w(f"var int[] VARI = array.from({', '.join(str(VAR[a['variant']]) for a in agents)})")
    w(f"var bool[] MAJ = array.from({', '.join('true' if a['group'] == 'majors' else 'false' for a in agents)})")
    w(f"var float[] M_BULL = {arr(m_t)}")
    w(f"var float[] S_BULL = {arr(s_t)}")
    w(f"var float[] M_BEAR = {arr(m_f)}")
    w(f"var float[] S_BEAR = {arr(s_f)}")
    w(f"var float[] M_NA = {arr(m_n)}")
    w(f"var float[] S_NA = {arr(s_n)}")
    w(f"var float[] G_MU = {arr(g['mean'], 8)}")
    w(f"var float[] G_SD = {arr(g['std'], 8)}")
    w(f"var float[] G_WL = {arr(g['w_loud'], 8)}")
    w(f"var float[] G_WQ = {arr(g['w_quiet'], 8)}")
    w(f"G_TL = {num(g['t_loud'], 6)}")
    w(f"G_TQ = {num(g['t_quiet'], 6)}")
    w(f"SIZE_A = {num(P['size_a'], 3)}")
    w(f"LOUD_PREC = \"{g['scores']['C']['loud_precision']:.0f}%\"")
    w("")
    w("// ───────────────────────── market and timeframe")
    w('base = syminfo.basecurrency')
    w('isMajor = base == "BTC" or base == "ETH" or base == "SOL"')
    w('isMeme = base == "DOGE" or base == "SHIB" or base == "PEPE" or base == "BONK" or base == "WIF" or base == "FLOKI"')
    w('trained = isMajor or isMeme')
    w('useMajor = isMajor or (not isMeme and iOther)')
    w('active = (trained or iOther) and timeframe.period == "60"')
    w('slip = useMajor ? 0.0002 : 0.001')
    w('enabled = array.from(' + ", ".join(f"a{k:02d}" for k in range(len(agents))) + ')')
    w("")
    w("// ───────────────────────── the 18 signals (identical formulas on 1h and inside the 4h request)")
    w("f_dn(k) => close[k + 1] < close[k + 6]")
    w("f_up(k) => close[k + 1] > close[k + 6]")
    w("f_all() =>")
    body = [
        "A = ta.atr(14)", "body = math.abs(close - open)", "rng = high - low", "upw = high - math.max(open, close)",
        "loww = math.min(open, close) - low", "isBull = close > open", "isBear = close < open", "big = rng >= 0.5 * A",
        "ham = loww >= 2 * body and upw <= 0.1 * rng and body >= 0.05 * rng and big",
        "inv = upw >= 2 * body and loww <= 0.1 * rng and body >= 0.05 * rng and big",
        "doji = body <= 0.1 * rng and big", "ins = high < high[1] and low > low[1]",
        "g5 = isBull and isBull[1] and isBull[2] and isBull[3] and isBull[4]",
        "r5 = isBear and isBear[1] and isBear[2] and isBear[3] and isBear[4]",
        "rvol = volume / ta.sma(volume, 20)[1]", "mf = ta.mfi(hlc3, 14)", "rsi14 = ta.rsi(close, 14)",
        "bbBasis = ta.sma(close, 20)", "bbDev = ta.stdev(close, 20)", "bbU = bbBasis + 2 * bbDev", "bbL = bbBasis - 2 * bbDev",
        "kcU = ta.ema(close, 20) + 2 * A", "ob = ta.obv", "obvHi = ob >= ta.highest(ob, 20)[1]",
        "cHi = close >= ta.highest(close, 20)[1]", "obvLead = obvHi and not cHi", "obvConf = obvHi and cHi",
        "don20 = close > ta.highest(high, 20)[1]",
        "upT = close > ta.ema(close, 50) and ta.ema(close, 21) > ta.ema(close, 50)"]
    for b in body:
        w("    " + b)
    for s in sigs:
        w(f"    s_{s} = {SNIP[s]}")
    w("    [" + ", ".join(f"s_{s}" for s in sigs) + ", A, upT]")
    w("")
    n_s = len(sigs)
    h1 = [f"h_{s}" for s in sigs]
    f4 = [f"q_{s}" for s in sigs]
    w("[" + ", ".join(h1) + ", atr1, upT1] = f_all()")
    w("[" + ", ".join(f4) + ", atr4, up4now] = request.security(syminfo.tickerid, \"240\", f_all(), lookahead=barmerge.lookahead_off)")
    w("sig1 = array.from(" + ", ".join(h1) + ")")
    w("sig4 = array.from(" + ", ".join(f4) + ")")
    w("is4hEnd = hour(time, \"UTC\") % 4 == 3")
    w("var bool up4 = false")
    w("var float atr4L = na")
    w("if is4hEnd")
    w("    up4 := up4now")
    w("    atr4L := atr4")
    w("")
    w("// ───────────────────────── trend and Bitcoin regime")
    w("up1 = ta.ema(close, 21) > ta.ema(close, 50) and close > ta.ema(close, 200)")
    w("upTrend = up1 and up4")
    w("f_btc() =>")
    w("    s200 = ta.sma(close, 200)")
    w("    r = na(s200) ? na : close > s200 ? 1.0 : 0.0")
    w("    r[1]")
    w('btcState = request.security("COINBASE:BTCUSD", "D", f_btc(), lookahead=barmerge.lookahead_on)')
    w("")
    w("// ───────────────────────── the volatility gate (trained logistic model, 14 features)")
    w("lg(x) => math.log(math.max(1e-6, x))")
    w("lr = nz(math.log(close / close[1]))")
    w("rms(k) => math.sqrt(math.sum(lr * lr, k) / k)")
    w("bbw = 4 * ta.stdev(close, 20) / ta.sma(close, 20)")
    w("r12 = (ta.highest(high, 12) - ta.lowest(low, 12)) / close")
    w("r72 = (ta.highest(high, 72) - ta.lowest(low, 72)) / close")
    w("hr = hour(time, \"UTC\")")
    w("dw = dayofweek(time, \"UTC\")")
    w("vsd = ta.stdev(volume, 168)")
    w("feat = array.from(1.0, lg(atr1 / ta.sma(atr1, 168)), lg(bbw / ta.sma(bbw, 168)), "
      "lg((math.sum(volume, 6) / 6 + 1e-12) / (ta.sma(volume, 168) + 1e-12)), lg(rms(24) / rms(168)), lg(r12 / ta.sma(r12, 168)), "
      "math.min(6.0, math.abs(close - close[12]) / atr1), math.min(6.0, (high - low) / atr1), "
      "math.sin(2 * math.pi * hr / 24), math.cos(2 * math.pi * hr / 24), dw == dayofweek.saturday or dw == dayofweek.sunday ? 1.0 : 0.0, "
      "lg(rms(6) / rms(168)), lg(r72 / ta.sma(r72, 168)), "
      "math.max(-4.0, math.min(4.0, (ta.sma(volume, 24) - ta.sma(volume, 168)) / (vsd > 0 ? vsd : 1e-12))))")
    w("zl = 0.0")
    w("zq = 0.0")
    w("bad = bar_index < 248")
    w("for k = 0 to array.size(feat) - 1")
    w("    x = array.get(feat, k)")
    w("    if na(x)")
    w("        bad := true")
    w("    else")
    w("        zz = (x - array.get(G_MU, k)) / array.get(G_SD, k)")
    w("        zl += zz * array.get(G_WL, k)")
    w("        zq += zz * array.get(G_WQ, k)")
    w("pLoud = 1 / (1 + math.exp(-zl))")
    w("pQuiet = 1 / (1 + math.exp(-zq))")
    w('gate = bad ? "U" : pLoud >= G_TL ? "L" : pQuiet >= G_TQ ? "Q" : "N"')
    w('gateOk = iGate == "Off" ? gate != "U" : iGate == "LOUD or NORMAL" ? (gate == "L" or gate == "N") : gate == "L"')
    w("")
    w("// ───────────────────────── the council: every enabled agent that fired asks the brain")
    w(f"var int[] last1 = array.new_int({n_s}, -100000)")
    w(f"var int[] last4 = array.new_int({n_s}, -100000)")
    w("keep1 = array.new_bool(" + str(n_s) + ", false)")
    w("keep4 = array.new_bool(" + str(n_s) + ", false)")
    w(f"for k = 0 to {n_s - 1}")
    w("    if array.get(sig1, k) and bar_index >= 210 and bar_index - array.get(last1, k) >= 12")
    w("        array.set(keep1, k, true)")
    w("        array.set(last1, k, bar_index)")
    w("    if is4hEnd and array.get(sig4, k) and bar_index - array.get(last4, k) >= 12")
    w("        array.set(keep4, k, true)")
    w("        array.set(last4, k, bar_index)")
    w("loud = gate == \"L\"")
    w("bestK = -1")
    w("bestScore = -1e9")
    w("bestM = 0.0")
    w("bestStop = 0.0")
    w("bestCost = 0.0")
    w("firing = 0")
    w("entryPx = close * 0.999")
    w(f"for k = 0 to {len(agents) - 1}")
    w("    s = array.get(SIG, k)")
    w("    four = array.get(IS4H, k)")
    w("    fired = four ? array.get(keep4, s) : array.get(keep1, s)")
    w("    v = array.get(VARI, k)")
    w("    cond = v == 0 or (v == 1 and loud) or (v == 2 and upTrend) or (v == 3 and loud and upTrend)")
    w("    if active and array.get(enabled, k) and array.get(MAJ, k) == useMajor and fired and cond")
    w("        firing += 1")
    w("        m = na(btcState) ? array.get(M_NA, k) : btcState == 1.0 ? array.get(M_BULL, k) : array.get(M_BEAR, k)")
    w("        se = na(btcState) ? array.get(S_NA, k) : btcState == 1.0 ? array.get(S_BULL, k) : array.get(S_BEAR, k)")
    w("        a = four ? atr4L : atr1")
    w("        stopD = iStopMult * a")
    w("        cost = ((iMaker + iTaker) / 100 + 2 * slip) / (stopD / entryPx)")
    w("        score = m - iZ * se")
    w("        if gateOk and not na(a) and cost <= iCostMax and score >= iTheta and score > bestScore")
    w("            bestScore := score")
    w("            bestK := k")
    w("            bestM := m")
    w("            bestStop := stopD")
    w("            bestCost := cost")
    w("")
    w("// ───────────────────────── one plan per market: limit entry, stop, target, time limit")
    w("var float pEntry = na")
    w("var float pStop = na")
    w("var float pTarget = na")
    w("var int pBar = na")
    w("var int pFill = na")
    w('var string pAgent = ""')
    w("var float pSize = 0.0")
    w("var float pQty = 0.0")
    w("var line lE = na")
    w("var line lS = na")
    w("var line lT = na")
    w("buyNow = false")
    w("sellMsg = \"\"")
    w("riskPct = useMajor ? iRiskMaj : iRiskMem")
    w("busy = not na(pEntry)")
    w("if barstate.isconfirmed and bestK >= 0 and not busy")
    w("    buyNow := true")
    w("    sz = math.max(0.5, math.min(1.5, 1 + SIZE_A * bestM)) * (bestCost > 0.20 ? 0.5 : 1.0)")
    w("    pEntry := entryPx")
    w("    pStop := entryPx - bestStop")
    w("    pTarget := entryPx + iTargetR * bestStop")
    w("    pBar := bar_index")
    w("    pFill := na")
    w("    pAgent := array.get(NAMES, bestK)")
    w("    pSize := sz")
    w("    pQty := math.min(iAccount * riskPct / 100 * sz / bestStop, iAccount / entryPx)")
    if strategy:
        w("    strategy.entry(\"ULTRON\", strategy.long, qty=pQty, limit=pEntry, comment=pAgent)")
        w("    strategy.exit(\"EXIT\", \"ULTRON\", stop=pStop, limit=pTarget)")
    w("    if iLines")
    w("        lE := line.new(bar_index, pEntry, bar_index + iHold, pEntry, color=cBuy, style=line.style_dashed, width=1)")
    w("        lS := line.new(bar_index, pStop, bar_index + iHold, pStop, color=cStop, style=line.style_dashed, width=1)")
    w("        lT := line.new(bar_index, pTarget, bar_index + iHold, pTarget, color=cTarget, style=line.style_dashed, width=1)")
    w("    if iPast")
    w("        label.new(bar_index, low, \"BUY\\n\" + pAgent, style=label.style_label_up, color=cBuy, textcolor=color.white, size=size.small)")
    w("else if busy and barstate.isconfirmed and bar_index > pBar")
    if strategy:
        w("    if na(pFill) and strategy.position_size > 0")
        w("        pFill := bar_index")
        w("    if na(pFill) and bar_index - pBar >= iOrderBars")
        w("        strategy.cancel(\"ULTRON\")")
        w("        sellMsg := \"CANCEL\"")
        w("    else if not na(pFill)")
        w("        if bar_index - pFill >= iHold")
        w("            strategy.close(\"ULTRON\", comment=\"96h\")")
        w("            sellMsg := \"TIME\"")
        w("        if strategy.position_size == 0 and bar_index > pFill")
        w("            sellMsg := sellMsg == \"\" ? \"DONE\" : sellMsg")
    else:
        w("    if na(pFill)")
        w("        if low <= pEntry")
        w("            pFill := bar_index")
        w("        else if bar_index - pBar >= iOrderBars")
        w("            sellMsg := \"CANCEL\"")
        w("    if not na(pFill) and sellMsg == \"\"")
        w("        if low <= pStop")
        w("            sellMsg := \"STOP\"")
        w("        else if high >= pTarget")
        w("            sellMsg := \"TARGET\"")
        w("        else if bar_index - pFill >= iHold")
        w("            sellMsg := \"TIME\"")
    w("    if sellMsg != \"\"")
    w("        if iPast and sellMsg != \"CANCEL\" and sellMsg != \"DONE\"")
    w("            label.new(bar_index, high, \"SELL\\n\" + sellMsg, style=label.style_label_down, "
      "color=sellMsg == \"TARGET\" ? cTarget : cStop, textcolor=color.white, size=size.small)")
    w("        pEntry := na")
    w("        pStop := na")
    w("        pTarget := na")
    w("        pFill := na")
    w("")
    w("// ───────────────────────── alerts (create ONE alert: condition ULTRON 25 → \"Any alert() function call\")")
    w("if buyNow")
    w("    msgB = iMsg == \"Readable\" ? \"ULTRON BUY \" + syminfo.ticker + \" · limit \" + str.tostring(pEntry, format.mintick) + "
      "\" · stop \" + str.tostring(pStop, format.mintick) + \" · sell \" + str.tostring(pTarget, format.mintick) + \" · size \" + "
      "str.tostring(pQty, \"#.####\") + \" · agent \" + pAgent + \" · edge \" + (bestM >= 0 ? \"+\" : \"\") + str.tostring(bestM, \"#.##\") + \"R\" : "
      "'{\"ultron\":\"BUY\",\"symbol\":\"' + syminfo.ticker + '\",\"agent\":\"' + pAgent + '\",\"entry\":' + "
      "str.tostring(pEntry, format.mintick) + ',\"stop\":' + str.tostring(pStop, format.mintick) + ',\"target\":' + "
      "str.tostring(pTarget, format.mintick) + ',\"qty\":' + str.tostring(pQty, \"#.########\") + ',\"edge_r\":' + "
      "str.tostring(bestM, \"#.###\") + ',\"gate\":\"' + gate + '\"}'")
    w("    alert(msgB, alert.freq_once_per_bar_close)")
    w("if sellMsg == \"STOP\" or sellMsg == \"TARGET\" or sellMsg == \"TIME\"")
    w("    why = sellMsg == \"TARGET\" ? \"target reached\" : sellMsg == \"STOP\" ? \"stop-loss hit\" : \"96 hours are up\"")
    w("    msgS = iMsg == \"Readable\" ? \"ULTRON SELL \" + syminfo.ticker + \" now · \" + why + \" · price \" + "
      "str.tostring(close, format.mintick) : '{\"ultron\":\"SELL\",\"symbol\":\"' + syminfo.ticker + '\",\"reason\":\"' + "
      "sellMsg + '\",\"price\":' + str.tostring(close, format.mintick) + '}'")
    w("    alert(msgS, alert.freq_once_per_bar_close)")
    if not strategy:
        w("alertcondition(buyNow, \"ULTRON BUY\", \"ULTRON 25: BUY {{ticker}} at {{close}} (see chart for entry, stop, target)\")")
        w("alertcondition(sellMsg == \"STOP\" or sellMsg == \"TARGET\" or sellMsg == \"TIME\", \"ULTRON SELL\", "
          "\"ULTRON 25: SELL {{ticker}} at {{close}}\")")
    w("")
    w("// ───────────────────────── chart")
    w("bgcolor(iGateBg and gate == \"L\" ? cLoud : na)")
    w("plotshape(buyNow and not iPast, \"Council buy\", shape.triangleup, location.belowbar, cBuy, size=size.tiny)")
    w("posT = iTablePos == \"Top right\" ? position.top_right : iTablePos == \"Top left\" ? position.top_left : "
      "iTablePos == \"Bottom right\" ? position.bottom_right : position.bottom_left")
    w("tsz = iTableSize == \"Tiny\" ? size.tiny : iTableSize == \"Normal\" ? size.normal : size.small")
    w("var table T = table.new(posT, 2, 10, bgcolor=color.new(color.white, 0), frame_color=color.new(#D9E0EB, 0), "
      "frame_width=1, border_color=color.new(#E9EEF5, 0), border_width=1)")
    w("cell(r, a, b, col) =>")
    w("    table.cell(T, 0, r, a, text_color=color.new(#56657C, 0), text_size=tsz, text_halign=text.align_left)")
    w("    table.cell(T, 1, r, b, text_color=col, text_size=tsz, text_halign=text.align_left)")
    w("if barstate.islast and iTable")
    w("    table.cell(T, 0, 0, \"ULTRON 25\", text_color=color.white, bgcolor=cBuy, text_size=tsz)")
    w("    table.cell(T, 1, 0, \"AI TRADE COUNCIL\", text_color=color.white, bgcolor=cBuy, text_size=tsz)")
    w("    if not active")
    w("        cell(1, \"Status\", timeframe.period != \"60\" ? \"Use the 1-hour chart\" : \"Not trained on \" + base, cStop)")
    w("    else")
    w("        gTxt = gate == \"L\" ? \"LOUD (big move likely)\" : gate == \"Q\" ? \"QUIET\" : gate == \"N\" ? \"NORMAL\" : \"warming up\"")
    w("        cell(1, \"Volatility\", gTxt, gate == \"L\" ? cBuy : color.new(#0A1426, 0))")
    w("        cell(2, \"LOUD right (test)\", LOUD_PREC, color.new(#0A1426, 0))")
    w("        cell(3, \"Trend 1h / 4h\", (up1 ? \"up\" : \"no\") + \" / \" + (up4 ? \"up\" : \"no\"), color.new(#0A1426, 0))")
    w("        cell(4, \"Bitcoin regime\", na(btcState) ? \"n/a\" : btcState == 1.0 ? \"above 200-day\" : \"below 200-day\", color.new(#0A1426, 0))")
    w("        cell(5, \"Agents firing now\", str.tostring(firing), color.new(#0A1426, 0))")
    w("        verdict = not na(pEntry) ? (na(pFill) ? \"BUY ORDER WAITING\" : \"IN TRADE\") : \"WAIT\"")
    w("        cell(6, \"Council\", verdict, not na(pEntry) ? cBuy : color.new(#56657C, 0))")
    w("        cell(7, \"Plan\", na(pEntry) ? \"—\" : \"buy \" + str.tostring(pEntry, format.mintick) + \" · stop \" + "
      "str.tostring(pStop, format.mintick) + \" · sell \" + str.tostring(pTarget, format.mintick), color.new(#0A1426, 0))")
    w("        cell(8, \"Agent / size\", na(pEntry) ? \"—\" : pAgent + \" · \" + str.tostring(pQty, \"#.####\") + \" \" + base, "
      "color.new(#0A1426, 0))")
    w("        cell(9, \"Not advice\", \"paper-test before real money\", color.new(#97A3B6, 0))")
    return "\n".join(L) + "\n"


def main():
    with open(os.path.join(HERE, "tv_model.json")) as fh:
        model = json.load(fh)
    for strategy, name in ((False, "ULTRON_25_indicator.pine"), (True, "ULTRON_25_strategy.pine")):
        src = build(model, strategy)
        with open(os.path.join(HERE, name), "w") as fh:
            fh.write(src)
        print(f"wrote {name}: {len(src.splitlines())} lines, {len(src):,} chars")


if __name__ == "__main__":
    main()
